# Generated by Django 4.1.7 on 2023-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('balance', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Баланс')),
                ('wallet_address', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Кошелек')),
            ],
        ),
    ]
