# Generated by Django 4.1.7 on 2023-03-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historytransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryTransfer',
        ),
    ]
